CC =gcc

all: play_again0 play_again1 play_again2 play_again3

play_again0: play_again0.c
	$(CC) -o play_again0 $^

play_again1: play_again1.c
	$(CC) -o play_again1 $^

play_again2: play_again2.c
	$(CC) -o play_again2 $^

play_again3: play_again3.c
	$(CC) -o play_again3 $^

clean:
	rm play_again0 play_again1 play_again2 play_again3